version: "3.7"
services:

  postgres:
    image: postgres:14.1-alpine
    container_name: ucraft_postgres_container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
    - ./ucraft-postgres-data:/var/lib/postgresql
    networks:
      - local-net

  redis:
    image: redis:6.2-alpine
    container_name: ucraft_redis_container
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./ucraft-redis-data:/data
    user: redis
    networks:
      - local-net

networks:
  local-net:
volumes:
  ucraft-postgres-data:
  ucraft-redis-data:
